"""Auto-generated migration

Revision ID: 7920b4839fe5
Revises: 
Create Date: 2023-08-29 16:07:40.360959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7920b4839fe5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kobo_data_a44ciRM8GHh5XHyJu4XEKn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kobo_id', sa.BigInteger(), nullable=False),
    sa.Column('I_suanID', sa.Text(), nullable=True),
    sa.Column('A_username', sa.Text(), nullable=True),
    sa.Column('A_Conglomerado', sa.Integer(), nullable=True),
    sa.Column('A_submission_date', sa.DateTime(), nullable=True),
    sa.Column('A_subparcela', sa.Text(), nullable=True),
    sa.Column('A_no_IA_individuo', sa.Integer(), nullable=True),
    sa.Column('A_category', sa.Text(), nullable=True),
    sa.Column('A_identificacion_arbol', sa.Text(), nullable=True),
    sa.Column('B_nombre_comun', sa.Text(), nullable=True),
    sa.Column('B_especie', sa.Text(), nullable=True),
    sa.Column('B_familia', sa.Text(), nullable=True),
    sa.Column('B_foto_arbol', sa.Text(), nullable=True),
    sa.Column('B_foto_tronco', sa.Text(), nullable=True),
    sa.Column('B_foto_hojas', sa.Text(), nullable=True),
    sa.Column('B_foto_flores', sa.Text(), nullable=True),
    sa.Column('B_foto_frutos', sa.Text(), nullable=True),
    sa.Column('C_arbol_vivo', sa.Text(), nullable=True),
    sa.Column('C_estado_arbol', sa.Text(), nullable=True),
    sa.Column('C_foto_arbol_afectada', sa.Text(), nullable=True),
    sa.Column('C_estado_descripcion', sa.Text(), nullable=True),
    sa.Column('C_arbol_muerto', sa.Text(), nullable=True),
    sa.Column('D_tallo_tipo', sa.Text(), nullable=True),
    sa.Column('D_fustes', sa.Integer(), nullable=True),
    sa.Column('D_equipo_1', sa.Text(), nullable=True),
    sa.Column('D_diametro_h_fuste_1', sa.Numeric(), nullable=True),
    sa.Column('D_diametro_h_fuste_2', sa.Numeric(), nullable=True),
    sa.Column('D_diametro_h_fuste_3', sa.Numeric(), nullable=True),
    sa.Column('D_diametro_h_fuste_4', sa.Numeric(), nullable=True),
    sa.Column('D_diametro_h_fuste_5', sa.Numeric(), nullable=True),
    sa.Column('D_diametro_2', sa.Text(), nullable=True),
    sa.Column('D_observacion', sa.Text(), nullable=True),
    sa.Column('D_azimut', sa.Integer(), nullable=True),
    sa.Column('D_distancia', sa.Text(), nullable=True),
    sa.Column('D_equipo_2', sa.Text(), nullable=True),
    sa.Column('D_altura', sa.Text(), nullable=True),
    sa.Column('D_altura_fuste_1', sa.Text(), nullable=True),
    sa.Column('D_altura_fuste_2', sa.Text(), nullable=True),
    sa.Column('D_altura_fuste_3', sa.Text(), nullable=True),
    sa.Column('D_altura_fuste_4', sa.Text(), nullable=True),
    sa.Column('D_altura_fuste_5', sa.Text(), nullable=True),
    sa.Column('D_altura_total', sa.Text(), nullable=True),
    sa.Column('D_HT_arbol_fuste_1', sa.Text(), nullable=True),
    sa.Column('D_HT_arbol_fuste_2', sa.Text(), nullable=True),
    sa.Column('D_HT_arbol_fuste_3', sa.Integer(), nullable=True),
    sa.Column('D_HT_arbol_fuste_4', sa.Integer(), nullable=True),
    sa.Column('D_HT_arbol_fuste_5', sa.Text(), nullable=True),
    sa.Column('D_colector', sa.Text(), nullable=True),
    sa.Column('D_observacion_general', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kobo_data_aAfruCuf8SbUd4jaztbmto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kobo_id', sa.BigInteger(), nullable=False),
    sa.Column('I_suanID', sa.Text(), nullable=True),
    sa.Column('A_username', sa.Text(), nullable=True),
    sa.Column('A_pointName', sa.Text(), nullable=True),
    sa.Column('A_image', sa.Text(), nullable=True),
    sa.Column('A_geotrace_name', sa.Text(), nullable=True),
    sa.Column('A_polygone_name', sa.Text(), nullable=True),
    sa.Column('B_ruta', sa.Text(), nullable=True),
    sa.Column('B_esquema', sa.Text(), nullable=True),
    sa.Column('C_cobertura', sa.Text(), nullable=True),
    sa.Column('C_tipo', sa.Text(), nullable=True),
    sa.Column('C_parcelared', sa.Text(), nullable=True),
    sa.Column('C_parcelaplant', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kobo_data_avJvoP4AH7Kj2LgVrdwdpj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kobo_id', sa.BigInteger(), nullable=False),
    sa.Column('I_accept', sa.Text(), nullable=True),
    sa.Column('A_postulante_name', sa.Text(), nullable=True),
    sa.Column('A_postulante_doctype', sa.Text(), nullable=True),
    sa.Column('A_postulante_id', sa.Text(), nullable=True),
    sa.Column('A_postulante_email', sa.Text(), nullable=True),
    sa.Column('A_asset_names', sa.Text(), nullable=True),
    sa.Column('A_description', sa.Text(), nullable=True),
    sa.Column('A_category', sa.Text(), nullable=True),
    sa.Column('A_vereda', sa.Text(), nullable=True),
    sa.Column('A_municipio', sa.Text(), nullable=True),
    sa.Column('A_matricula', sa.Text(), nullable=True),
    sa.Column('A_ficha_catastral', sa.Text(), nullable=True),
    sa.Column('B_owner', sa.Text(), nullable=True),
    sa.Column('B_owner_doctype', sa.Text(), nullable=True),
    sa.Column('B_owner_id', sa.Text(), nullable=True),
    sa.Column('B_owner_certificado', sa.Text(), nullable=True),
    sa.Column('C_plano_predio', sa.Text(), nullable=True),
    sa.Column('D_area', sa.Integer(), nullable=True),
    sa.Column('D_actual_use', sa.Text(), nullable=True),
    sa.Column('D_area_potrero', sa.Integer(), nullable=True),
    sa.Column('D_especie_plantaciones1', sa.Text(), nullable=True),
    sa.Column('D_ha_plantaciones1', sa.Integer(), nullable=True),
    sa.Column('D_especie_plantaciones2', sa.Text(), nullable=True),
    sa.Column('D_ha_plantaciones2', sa.Integer(), nullable=True),
    sa.Column('D_especie_plantaciones3', sa.Integer(), nullable=True),
    sa.Column('D_ha_plantaciones3', sa.Text(), nullable=True),
    sa.Column('D_especie_frutales1', sa.Text(), nullable=True),
    sa.Column('D_ha_frutales1', sa.Integer(), nullable=True),
    sa.Column('D_especie_frutales2', sa.Text(), nullable=True),
    sa.Column('D_ha_frutales2', sa.Integer(), nullable=True),
    sa.Column('D_especie_otros', sa.Text(), nullable=True),
    sa.Column('D_ha_otros', sa.Integer(), nullable=True),
    sa.Column('D_replace_use', sa.Text(), nullable=True),
    sa.Column('D_replace_potrero_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_potrero_use', sa.Integer(), nullable=True),
    sa.Column('D_replace_plantaciones1_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_plantaciones1_use', sa.Integer(), nullable=True),
    sa.Column('D_replace_plantaciones2_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_plantaciones2_use', sa.Integer(), nullable=True),
    sa.Column('D_replace_plantaciones3_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_plantaciones3_use', sa.Integer(), nullable=True),
    sa.Column('D_replace_frutales1_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_frutales1_use', sa.Integer(), nullable=True),
    sa.Column('D_replace_frutales2_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_frutales2_use', sa.Integer(), nullable=True),
    sa.Column('D_replace_otros_use', sa.Text(), nullable=True),
    sa.Column('D_replace_ha_otros_use', sa.Integer(), nullable=True),
    sa.Column('E_restriccion_desc', sa.Text(), nullable=True),
    sa.Column('E_resctriccion_other', sa.Text(), nullable=True),
    sa.Column('F_nacimiento_agua', sa.Text(), nullable=True),
    sa.Column('F_nacimiento_agua_quantity', sa.Integer(), nullable=True),
    sa.Column('F_agua_concede', sa.Text(), nullable=True),
    sa.Column('F_agua_concede_entity', sa.Text(), nullable=True),
    sa.Column('F_amenazas_defo_desc', sa.Text(), nullable=True),
    sa.Column('F_conservacion_desc', sa.Text(), nullable=True),
    sa.Column('F_especies_fauna', sa.Text(), nullable=True),
    sa.Column('F_especies_mamiferos', sa.Text(), nullable=True),
    sa.Column('F_especies_aves', sa.Text(), nullable=True),
    sa.Column('F_especies_flora', sa.Text(), nullable=True),
    sa.Column('G_habita_predio', sa.Text(), nullable=True),
    sa.Column('G_Temporal_permanente', sa.Text(), nullable=True),
    sa.Column('G_habita_years', sa.Text(), nullable=True),
    sa.Column('G_viviendas_number', sa.Integer(), nullable=True),
    sa.Column('G_familias', sa.Integer(), nullable=True),
    sa.Column('G_familias_miembros', sa.Integer(), nullable=True),
    sa.Column('G_vias_state', sa.Text(), nullable=True),
    sa.Column('G_distancia_predio_municipal', sa.Integer(), nullable=True),
    sa.Column('G_transport_mean', sa.Text(), nullable=True),
    sa.Column('G_caminos_existence', sa.Text(), nullable=True),
    sa.Column('G_risks_erosion_derrumbe', sa.Text(), nullable=True),
    sa.Column('H_asistance_desc', sa.Text(), nullable=True),
    sa.Column('H_aliados_estrategicos_desc', sa.Text(), nullable=True),
    sa.Column('H_grupo_comunitario_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kobo_data_avJvoP4AH7Kj2LgVrdwdpj')
    op.drop_table('kobo_data_aAfruCuf8SbUd4jaztbmto')
    op.drop_table('kobo_data_a44ciRM8GHh5XHyJu4XEKn')
    # ### end Alembic commands ###
