"""Creation of kobo forms table

Revision ID: 03b7ca12fbaf
Revises: 592518ff7275
Create Date: 2023-05-10 18:23:44.750440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b7ca12fbaf'
down_revision = '592518ff7275'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kobo_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('koboform_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.Text(), nullable=True),
    sa.Column('deployment_active', sa.Text(), nullable=True),
    sa.Column('deployment_count', sa.Integer(), nullable=True),
    sa.Column('owner_username', sa.Text(), nullable=True),
    sa.Column('has_deployment', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kobo_forms')
    # ### end Alembic commands ###
