"""Auto-generated migration

Revision ID: 2ed688216eac
Revises: a1b0ed363324
Create Date: 2023-07-14 14:20:39.371629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed688216eac'
down_revision = 'a1b0ed363324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kobo_data_avJvoP4AH7Kj2LgVrdwdpj', sa.Column('A_description', sa.Text(), nullable=True))
    op.add_column('kobo_data_avJvoP4AH7Kj2LgVrdwdpj', sa.Column('A_category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kobo_data_avJvoP4AH7Kj2LgVrdwdpj', 'A_category')
    op.drop_column('kobo_data_avJvoP4AH7Kj2LgVrdwdpj', 'A_description')
    # ### end Alembic commands ###
