"""Create Kobo data table for form 1

Revision ID: 69816cd98099
Revises: 03b7ca12fbaf
Create Date: 2023-05-12 17:32:57.457929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69816cd98099'
down_revision = '03b7ca12fbaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kobo_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_form', sa.Integer(), nullable=True),
    sa.Column('id_suan', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('phonenumber', sa.Text(), nullable=True),
    sa.Column('kobo_id', sa.BigInteger(), nullable=True),
    sa.Column('submission_time', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('geopoint_map', sa.Text(), nullable=True),
    sa.Column('annotate', sa.Text(), nullable=True),
    sa.Column('text_001', sa.Text(), nullable=True),
    sa.Column('geotrace', sa.Text(), nullable=True),
    sa.Column('text_002', sa.Text(), nullable=True),
    sa.Column('geoshape', sa.Text(), nullable=True),
    sa.Column('geopoint_hide', sa.Text(), nullable=True),
    sa.Column('audit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_form'], ['kobo_forms.id'], ),
    sa.ForeignKeyConstraint(['id_suan'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kobo_data')
    # ### end Alembic commands ###
