"""Auto-generated migration

Revision ID: a1b0ed363324
Revises: 4e4bc6161022
Create Date: 2023-07-10 14:22:55.226947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b0ed363324'
down_revision = '4e4bc6161022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kobo_data_aAfruCuf8SbUd4jaztbmto', sa.Column('B_ruta', sa.Text(), nullable=True))
    op.add_column('kobo_data_aAfruCuf8SbUd4jaztbmto', sa.Column('B_esquema', sa.Text(), nullable=True))
    op.add_column('kobo_data_aAfruCuf8SbUd4jaztbmto', sa.Column('C_cobertura', sa.Text(), nullable=True))
    op.add_column('kobo_data_aAfruCuf8SbUd4jaztbmto', sa.Column('C_tipo', sa.Text(), nullable=True))
    op.add_column('kobo_data_aAfruCuf8SbUd4jaztbmto', sa.Column('C_parcelared', sa.Text(), nullable=True))
    op.add_column('kobo_data_aAfruCuf8SbUd4jaztbmto', sa.Column('C_parcelaplant', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kobo_data_aAfruCuf8SbUd4jaztbmto', 'C_parcelaplant')
    op.drop_column('kobo_data_aAfruCuf8SbUd4jaztbmto', 'C_parcelared')
    op.drop_column('kobo_data_aAfruCuf8SbUd4jaztbmto', 'C_tipo')
    op.drop_column('kobo_data_aAfruCuf8SbUd4jaztbmto', 'C_cobertura')
    op.drop_column('kobo_data_aAfruCuf8SbUd4jaztbmto', 'B_esquema')
    op.drop_column('kobo_data_aAfruCuf8SbUd4jaztbmto', 'B_ruta')
    # ### end Alembic commands ###
