"""Project schema modification

Revision ID: fa6e09fd8fa8
Revises: 7ebce46b609e
Create Date: 2023-05-06 17:27:30.436532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6e09fd8fa8'
down_revision = '7ebce46b609e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('suanid', sa.UUID(), nullable=False))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('categoryid', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('projects', 'sector')
    op.drop_column('projects', 'url')
    op.drop_column('projects', 'version_id')
    op.drop_column('projects', 'asset_type')
    op.drop_column('projects', 'uid')
    op.drop_column('projects', 'owner')
    op.drop_column('projects', 'country')
    op.drop_column('projects', 'kind')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('asset_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('version_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('sector', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'categoryid')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'suanid')
    # ### end Alembic commands ###
