[tool.poetry]
name = "suan-trazabilidad"
version = "0.1.0"
description = ""
authors = ["Moxie <moxie@suan.global>"]
readme = "README.md"
packages = [{include = "suan_trazabilidad"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
python-decouple = "^3.8"
requests = "^2.30.0"
uvicorn = "^0.22.0"
pandas = "<2.0.0"
openpyxl = "^3.1.2"
numpy = "^1.24.3"
pyqldb = "^3.2.3"
passlib = "^1.7.4"
koios-api = "^1.1.0.0"
python-dotenv = "^1.0.0"
boto3 = "^1.34.58"
uplc = "^0.6.7"
pyaiken = "^0.5.5"
streamlit = "^1.35.0"
alembic = "^1.13.2"
psycopg2 = "^2.9.9"
rocketry = "^2.5.1"
fastapi = "^0.111.1"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
ogmios = "^1.1.1"
websockets = "^12.0"
opshin = "^0.22.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.1"
pytest-cov = "^5.0.0"
isort = "^5.13.2"
flake8 = "^7.0.0"
bandit = "^1.7.8"
safety = "^3.2.0"
python-semantic-release = "^9.8.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
repo_dir = "/home/cardanodatos/suan/suan-trazabilidad"
no_git_verify = false
tag_format = "v{version}"
# ... other configs
version_variables = ["suantrazabilidad/__init__.py:__version__"]
upload_to_pypi = true
pypi_token = "${PYPI_TOKEN}"
vcs_token = "${GH_TOKEN}"

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true

