[tool.poetry]
name = "suan-trazabilidad"
version = "0.1.0"
description = ""
authors = ["Moxie <moxie@suan.global>"]
readme = "README.md"
packages = [{include = "suan_trazabilidad"}]

[tool.poetry.dependencies]
python = "^3.11"
alembic = "^1.10.4"
pydantic = {extras = ["email"], version = "^1.10.7"}
psycopg2-binary = "^2.9.6"
python-decouple = "^3.8"
psycopg2 = "^2.9.6"
requests = "^2.30.0"
fastapi = "^0.95.1"
uvicorn = "^0.22.0"
pytest = "^7.3.1"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
