"""Creation of tables

Revision ID: 361bd9798b1e
Revises: 
Create Date: 2024-07-03 13:11:43.946146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361bd9798b1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_token_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.Text(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('utxo', sa.Text(), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('txid', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_token_access_id'), 'claim_token_access', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_token_access_id'), table_name='claim_token_access')
    op.drop_table('claim_token_access')
    # ### end Alembic commands ###
