# copilot/trazabilidad/addons/rabbitmq.yml
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  App:
    Type: String
    Description: "trazabilidad"
  Env:
    Type: String
    Description: "test"
  Name:
    Type: String
    Description: "rabbitmq"
  AmazonMQBrokerUser:
    Description: The user to access the Amazon MQ broker.
    Type: String
    Default: rabbitmquser
    MinLength: 2
    ConstraintDescription: The Amazon MQ broker user is required.
  AmazonMQBrokerPassword:
    Description: The password to access the Amazon MQ broker. Min 12 characters
    Type: String
    Default: rabbitmquser
    MinLength: 10
    ConstraintDescription: The Amazon MQ broker password is required.
    NoEcho: true
Resources:
  RabbitMQCluster:
    Type: AWS::AmazonMQ::Broker
    Properties: 
      BrokerName: !Sub "${App}-${Env}-rabbitmq"
      EngineType: RABBITMQ
      # EngineVersion: 3.13.6
      HostInstanceType: mq.t3.micro
      AutoMinorVersionUpgrade: true
      DeploymentMode: SINGLE_INSTANCE
      PubliclyAccessible: true
      Logs:
        General: true
      Users:
        - ConsoleAccess: true
          Groups:
            - admin
          Username: !Ref AmazonMQBrokerUser
          Password: !Ref AmazonMQBrokerPassword
      # SecurityGroups:
      #   - !Ref RabbitMQSecurityGroup
  StoreRabbitMQEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/trazabilidad/rabbitmq-endpoint"
      Type: String
      Value: !Sub "${RabbitMQCluster}.mq.${AWS::Region}.amazonaws.com"
  
  # StoreRabbitMQUser:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: !Sub "/trazabilidad/rabbitmq-user"
  #     Type: String
  #     Value: !Ref AmazonMQBrokerUser

  # StoreRabbitMQPassword:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: !Sub "/trazabilidad/rabbitmq-password"
  #     Type: String
  #     Value: !Ref AmazonMQBrokerPassword

Outputs:
  RabbitMQEndpoint:
    Description: RabbitMQ Broker Endpoint
    Value: !Sub "${RabbitMQCluster}.mq.${AWS::Region}.amazonaws.com"
    Export:
      Name: RabbitMQEndpoint

  RabbitMQWebConsole:
    Description: RabbitMQ Web console
    Value: !Sub "https://${RabbitMQCluster}.mq.${AWS::Region}.amazonaws.com"

  RabbitMQUsername:
    Description: RabbitMQ Username
    Value: !Ref AmazonMQBrokerUser
    Export:
      Name: RabbitMQUsername

  RabbitMQPassword:
    Description: RabbitMQ Password
    Value: !Ref AmazonMQBrokerPassword
    Export:
      Name: RabbitMQPassword