AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: String
    Description: "The VPC ID where the Redis cluster will be deployed."
    Default: "vpc-09a24d67ca6e165cf"
  PrivateSubnets:
    Type: CommaDelimitedList
    Description: "The list of private subnets for the Redis cluster."
    Default: "subnet-0aef1333f7b247d81,subnet-0f2acefcdf398c3c7"

Resources:
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.micro
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !GetAtt RedisSecurityGroup.GroupId
      CacheSubnetGroupName: !Ref CacheSubnetGroup

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis security group
      VpcId: !Ref VpcId

  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Redis subnet group"
      SubnetIds: !Ref PrivateSubnets

  StoreRedisEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/trazabilidad/redis-endpoint"
      Type: String
      Value: !GetAtt RedisCluster.RedisEndpoint.Address

Outputs:
  RedisEndpoint:
    Description: Redis Cluster Endpoint
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      # Name: RedisEndpoint
      Name: !Sub "${AWS::StackName}-RedisEndpoint"
